#!/usr/bin/env bats

setup() {
  repo_root=$(CDPATH= cd -- "$BATS_TEST_DIRNAME/.." && pwd -P)
  active_repo=$repo_root
  test_root=$(mktemp -d "${TMPDIR:-/tmp}/agent-dotfiles-test.XXXXXX")
  dest_home="$test_root/home"
  agents_file="$test_root/generated/AGENTS.md"
}

teardown() {
  rm -rf "$test_root"
}

run_apply() {
  run make --no-print-directory -C "$active_repo" apply \
    "DEST_HOME=$dest_home" "AGENTS_FILE=$agents_file"
}

run_apply_without_input() {
  run sh -c 'make --no-print-directory -C "$1" apply "DEST_HOME=$2" "AGENTS_FILE=$3" </dev/null' \
    sh "$active_repo" "$dest_home" "$agents_file"
}

run_apply_with_input() {
  input=$1
  run sh -c 'printf "%b" "$1" | make --no-print-directory -C "$2" apply "DEST_HOME=$3" "AGENTS_FILE=$4"' \
    sh "$input" "$active_repo" "$dest_home" "$agents_file"
}

run_apply_with_topics() {
  topics=$1
  run make --no-print-directory -C "$active_repo" apply \
    "DEST_HOME=$dest_home" "AGENTS_FILE=$agents_file" "TOPIC_FILES=$topics"
}

expected_claude() {
  printf '%s\n\n' '<!-- managed-by: agent-dotfiles -->'
  printf '%s\n\n' '# Global preferences'
  printf '%s\n\n' 'Each topic is imported from the agent-dotfiles repository.'
  printf '@%s/commits.md\n' "$active_repo"
  printf '@%s/task-starting.md\n' "$active_repo"
  printf '@%s/planning.md\n' "$active_repo"
  printf '@%s/code-comments.md\n' "$active_repo"
}

expected_agents() {
  printf '%s\n' '<!-- managed-by: agent-dotfiles -->'
  printf '%s\n\n' '<!-- Generated by make apply. Do not edit directly. -->'
  cat "$active_repo/commits.md"
  printf '\n'
  cat "$active_repo/task-starting.md"
  printf '\n'
  cat "$active_repo/planning.md"
  printf '\n'
  cat "$active_repo/code-comments.md"
  printf '\n'
}

make_fixture_repo() {
  active_repo="$test_root/repo with spaces"
  mkdir -p "$active_repo/scripts"
  cp "$repo_root/Makefile" "$active_repo/Makefile"
  cp "$repo_root/scripts/apply.sh" "$active_repo/scripts/apply.sh"
  cp "$repo_root/commits.md" "$active_repo/commits.md"
  cp "$repo_root/task-starting.md" "$active_repo/task-starting.md"
  cp "$repo_root/planning.md" "$active_repo/planning.md"
  cp "$repo_root/code-comments.md" "$active_repo/code-comments.md"
}

@test "fresh apply renders ordered documents and an absolute Codex symlink" {
  run_apply

  [ "$status" -eq 0 ]
  [ "$output" = "Applied Claude and Codex instructions from $active_repo" ]
  cmp <(expected_claude) "$dest_home/.claude/CLAUDE.md"
  cmp <(expected_agents) "$agents_file"
  [ "$(head -n 1 "$dest_home/.claude/CLAUDE.md")" = '<!-- managed-by: agent-dotfiles -->' ]
  [ "$(head -n 1 "$agents_file")" = '<!-- managed-by: agent-dotfiles -->' ]
  [ -L "$dest_home/.codex/AGENTS.md" ]
  [ "$(readlink "$dest_home/.codex/AGENTS.md")" = "$agents_file" ]

  run_apply_without_input

  [ "$status" -eq 0 ]
  [ "$output" = "Applied Claude and Codex instructions from $active_repo" ]
  cmp <(expected_claude) "$dest_home/.claude/CLAUDE.md"
  cmp <(expected_agents) "$agents_file"
  [ -L "$dest_home/.codex/AGENTS.md" ]
  [ "$(readlink "$dest_home/.codex/AGENTS.md")" = "$agents_file" ]
}

@test "managed destinations refresh without prompting" {
  mkdir -p "$(dirname "$dest_home/.claude/CLAUDE.md")" "$(dirname "$agents_file")" "$dest_home/.codex"
  printf '%s\nold Claude\n' '<!-- managed-by: agent-dotfiles -->' >"$dest_home/.claude/CLAUDE.md"
  printf '%s\nold agents\n' '<!-- managed-by: agent-dotfiles -->' >"$agents_file"
  printf '%s\nold Codex\n' '<!-- managed-by: agent-dotfiles -->' >"$dest_home/.codex/AGENTS.md"

  run_apply_without_input

  [ "$status" -eq 0 ]
  [ "$output" = "Applied Claude and Codex instructions from $active_repo" ]
  cmp <(expected_claude) "$dest_home/.claude/CLAUDE.md"
  cmp <(expected_agents) "$agents_file"
  [ -L "$dest_home/.codex/AGENTS.md" ]
  [ "$(readlink "$dest_home/.codex/AGENTS.md")" = "$agents_file" ]
}

@test "a marker outside line one does not establish ownership" {
  claude_file="$dest_home/.claude/CLAUDE.md"
  mkdir -p "$(dirname "$claude_file")"
  printf 'unmanaged heading\n%s\n' '<!-- managed-by: agent-dotfiles -->' >"$claude_file"

  run_apply_with_input 'n\n'

  [ "$status" -ne 0 ]
  [ "$(cat "$claude_file")" = "$(printf 'unmanaged heading\n%s' '<!-- managed-by: agent-dotfiles -->')" ]
  [[ "$output" == *"--- $claude_file"* ]]
  [[ "$output" == *'[y/N]'* ]]
  [ ! -e "$agents_file" ]
  [ ! -e "$dest_home/.codex/AGENTS.md" ]
}

@test "declining a later unmanaged conflict leaves earlier managed files unchanged" {
  claude_file="$dest_home/.claude/CLAUDE.md"
  codex_file="$dest_home/.codex/AGENTS.md"
  mkdir -p "$(dirname "$claude_file")" "$(dirname "$agents_file")" "$(dirname "$codex_file")"
  printf '%s\nold Claude\n' '<!-- managed-by: agent-dotfiles -->' >"$claude_file"
  printf '%s\nold agents\n' '<!-- managed-by: agent-dotfiles -->' >"$agents_file"
  wrong_target="$test_root/foreign AGENTS.md"
  printf 'foreign Codex\n' >"$wrong_target"
  ln -s "$wrong_target" "$codex_file"

  run_apply_with_input 'n\n'

  [ "$status" -ne 0 ]
  [ "$(cat "$claude_file")" = "$(printf '%s\nold Claude' '<!-- managed-by: agent-dotfiles -->')" ]
  [ "$(cat "$agents_file")" = "$(printf '%s\nold agents' '<!-- managed-by: agent-dotfiles -->')" ]
  [ "$(readlink "$codex_file")" = "$wrong_target" ]
  [[ "$output" == *"Current Codex symlink target: $wrong_target"* ]]
  [[ "$output" == *'[y/N]'* ]]
}

@test "accepting an unmanaged regular file replaces it" {
  claude_file="$dest_home/.claude/CLAUDE.md"
  mkdir -p "$(dirname "$claude_file")"
  printf 'personal instructions\n' >"$claude_file"

  run_apply_with_input 'Y\n'

  [ "$status" -eq 0 ]
  cmp <(expected_claude) "$claude_file"
  cmp <(expected_agents) "$agents_file"
  [ "$(readlink "$dest_home/.codex/AGENTS.md")" = "$agents_file" ]
}

@test "EOF declines an unmanaged conflict without writing" {
  claude_file="$dest_home/.claude/CLAUDE.md"
  mkdir -p "$(dirname "$claude_file")"
  printf 'personal instructions\n' >"$claude_file"

  run_apply_without_input

  [ "$status" -ne 0 ]
  [ "$(cat "$claude_file")" = 'personal instructions' ]
  [[ "$output" == *'[y/N]'* ]]
  [ ! -e "$agents_file" ]
}

@test "a diff error aborts without destination changes" {
  claude_file="$dest_home/.claude/CLAUDE.md"
  mkdir -p "$(dirname "$claude_file")"
  printf 'private instructions\n' >"$claude_file"
  chmod 000 "$claude_file"

  run_apply_with_input 'Y\n'

  chmod 600 "$claude_file"
  [ "$status" -ne 0 ]
  [ "$(cat "$claude_file")" = 'private instructions' ]
  [ ! -e "$agents_file" ]
  [ ! -e "$dest_home/.codex/AGENTS.md" ]
}

@test "a broken Codex symlink shows its raw target and a null diff before prompting" {
  claude_file="$dest_home/.claude/CLAUDE.md"
  codex_file="$dest_home/.codex/AGENTS.md"
  mkdir -p "$(dirname "$claude_file")" "$(dirname "$agents_file")" "$(dirname "$codex_file")"
  printf '%s\nold Claude\n' '<!-- managed-by: agent-dotfiles -->' >"$claude_file"
  printf '%s\nold agents\n' '<!-- managed-by: agent-dotfiles -->' >"$agents_file"
  broken_target='../missing target'
  ln -s "$broken_target" "$codex_file"

  run_apply_with_input 'n\n'

  [ "$status" -ne 0 ]
  [ "$(readlink "$codex_file")" = "$broken_target" ]
  [[ "$output" == *"Current Codex symlink target: $broken_target"* ]]
  [[ "$output" == *'--- /dev/null'* ]]
  [[ "$output" == *'<!-- managed-by: agent-dotfiles -->'* ]]
  [[ "$output" == *'[y/N]'* ]]
}

@test "accepting a Codex symlink to an existing directory replaces the symlink atomically" {
  codex_file="$dest_home/.codex/AGENTS.md"
  referent="$test_root/existing Codex directory"
  mkdir -p "$(dirname "$codex_file")" "$referent"
  ln -s "$referent" "$codex_file"

  run_apply_with_input 'Y\n'

  [ "$status" -eq 0 ]
  [[ "$output" == *'--- '* ]]
  [[ "$output" == *'+++ '* ]]
  [[ "$output" == *'Codex symlink resolves to a non-regular target.'* ]]
  [[ "$output" == *'[y/N]'* ]]
  [[ "$output" != *'--- /dev/null'* ]]
  [[ "$output" != *'Current Codex symlink target:'* ]]
  [ -L "$codex_file" ]
  [ "$(readlink "$codex_file")" = "$agents_file" ]
  [ -z "$(find "$referent" -mindepth 1 -print -quit)" ]
}

@test "directories at destinations are rejected without replacing anything" {
  claude_file="$dest_home/.claude/CLAUDE.md"
  mkdir -p "$claude_file"

  run_apply

  [ "$status" -ne 0 ]
  [[ "$output" == *"Unsupported destination type: $claude_file"* ]]
  [ -d "$claude_file" ]
  [ ! -e "$agents_file" ]
  [ ! -e "$dest_home/.codex/AGENTS.md" ]
}

@test "missing topics fail before destination files are written" {
  run_apply_with_topics 'commits.md missing.md'

  [ "$status" -ne 0 ]
  [[ "$output" == *"Topic file is missing or unreadable: $active_repo/missing.md"* ]]
  [ ! -e "$dest_home/.claude/CLAUDE.md" ]
  [ ! -e "$agents_file" ]
  [ ! -e "$dest_home/.codex/AGENTS.md" ]
}

@test "unreadable topics fail before destination files are written" {
  make_fixture_repo
  chmod 000 "$active_repo/commits.md"

  run_apply

  [ "$status" -ne 0 ]
  [[ "$output" == *"Topic file is missing or unreadable: $active_repo/commits.md"* ]]
  [ ! -e "$dest_home/.claude/CLAUDE.md" ]
  [ ! -e "$agents_file" ]
  [ ! -e "$dest_home/.codex/AGENTS.md" ]
}

@test "paths containing spaces install atomically and link exactly" {
  dest_home="$test_root/home with spaces"
  agents_file="$test_root/generated files/AGENTS.md"

  run_apply

  [ "$status" -eq 0 ]
  cmp <(expected_claude) "$dest_home/.claude/CLAUDE.md"
  cmp <(expected_agents) "$agents_file"
  [ "$(readlink "$dest_home/.codex/AGENTS.md")" = "$agents_file" ]
}
